import {
  IconExclamationCircle,
  IconLocation,
  IconBrandHipchat,
  IconFileTypePdf,
  IconX,
  IconUnlink,
  IconPlus,
  IconCloudUpload,
  IconTrash,
  IconUpload,
  IconBrandOpenai,
  IconCertificate,
  IconCheck,
  IconMessage,
  IconVariablePlus,
  IconAlignCenter,
  IconInfoSquareRounded,
} from 'angular-tabler-icons/icons';

const icons = {
  IconExclamationCircle,
  IconLocation,
  IconInfoSquareRounded,
  IconBrandHipchat,
  IconFileTypePdf,
  IconX,
  IconUnlink,
  IconPlus,
  IconCloudUpload,
  IconTrash,
  IconUpload,
  IconBrandOpenai,
  IconCertificate,
  IconCheck,
  IconMessage,
  IconVariablePlus,
  IconAlignCenter,
} as const;

export { icons as TABLER_ICONS };
